type apiGatewayHttpEvent = {
  path: String,
  headers: Hash[Symbol, String],
  httpMethod: String,
  requestContext: Hash[Symbol, String],
  isBase64Encoded: bool,
  pathParameters: Hash[Symbol, String],
  queryStringParameters: Hash[Symbol, String],
  resource: String,
  stageVariables: Hash[Symbol, String],
  body?: String,
}