type cloudWatchLogsEvent = {
  awslogs: cloudWatchLogsRawData
}

type cloudWatchLogsRawData = {
  data: string
}

type cloudWatchLogsData = {
  owner: String,
  logGroup: String,
  logStream: String,
  subscriptionFilters: Array[String],
  messageType: String,
  logEvents: Array[cloudWatchLogEvent]
}

type cloudWatchLogEvent = {
  id: String,
  timestamp: Integer,
  message: String
}
