type snsEvent = { Records: Array[snsEventRecords] }
type snsEventRecords = {
  EventVersion: String,
  EventSubscriptionArn: String,
  EventSource: String,
  Sns: snsEntity
}
type snsEntity = {
  SignatureVersion: String,
  Timestamp: String,
  Signature: String,
  SigningCertUrl: String,
  MessageId: String,
  Message: String,
  MessageAttributes: Hash[Symbol, snsMessageAttributes],
  Type: String,
  UnsubscribeUrl: String,
  TopicArn: String,
  Subject: String
}
type snsMessageAttributes = {
  Type: String,
  Value: String
}

