module ActiveFunction
  type awsConfigEvent = {
    accountId: String,
    configRuleId: String,
    configRuleName: String,
    configRuleArn: String,
    eventLeftScope: bool, 
    executionRoleArn: String,
    invokingEvent: String,
    resultToken: String,
    ruleParameters: String,
    version: String
  }
end