module ActiveFunction
  type s3Event = { Records: Array[s3EventRecord] }
  type s3EventRecord = {
    eventVersion: String,
    eventSource: String,
    awsRegion: String,
    eventTime: String,
    eventName: String,
    userIdentity: s3UserIdentity,
    requestParameters: s3RequestParameters,
    responseElements: Hash[String, String],
    s3: s3Entity
  }
  type s3UserIdentity = { principalId: String }
  type s3RequestParameters = { sourceIPAddress: String }
  type s3Entity = {
    schemaVersion: String, 
    configurationId: String,
    bucket: s3Bucket,
    object: s3Object
  }
  type s3Bucket = {
    name: String,
    ownerIdentity: s3UserIdentity,
    arn: String
  }
  type s3Object = {
    key: String,
    size: Integer,
    eTag: String,
    sequencer: String
  }
end 
