module ActiveFunction
  type sesEvent = {
    Records: Array[sesRecord]
  }

  type sesRecord = {
    eventVersion: String,
    eventSource: String,
    ses: simpleEmailService
  }

  type simpleEmailService = {
    mail: simpleEmailMessage,
    receipt: simpleEmailReceipt
  }

  type simpleEmailMessage = {
    timestamp: String,
    source: String,
    messageId: String,
    destination: Array[String],
    headersTruncated: bool,
    headers: Array[sesHeader],
    commonHeaders: commonHeaders
  }

  type sesHeader = {
    name: String,
    value: String
  }

  type commonHeaders = {
    from: Array[String],
    to: Array[String],
    date: String,
    messageId: String,
    subject: String
  }

  type simpleEmailReceipt = {
    recipients: Array[String],
    timestamp: String, 
    spamVerdict: simpleEmailVerdict,
    virusVerdict: simpleEmailVerdict,
    spfVerdict: simpleEmailVerdict,
    dkimVerdict: simpleEmailVerdict,
    dmarcVerdict: simpleEmailVerdict,
    processingTimeMillis: Integer,
    action: simpleEmailAction,
  }

  type simpleEmailVerdict = {
    status: String
  }

  type simpleEmailAction = {
    type: String,
    topicArn: String,
    position: Integer
  }
end