module Kopilka 
  class Options 
    attr_reader level?: ::Logger::Severity
    attr_reader formatter?: ::Logger::Formatter
  end

  class Logger
    def error: (Exception err) -> void
    def info: (Exception err) -> void
    def logger: -> ::Logger

    class LoggerBuilder
      DEFAULT_OPTIONS : Options

      def initialize: (Options options) -> void
      
      private
      def build: -> ::Logger
    end 
  end 
end 