module ActiveFunction
  type hash = Hash[untyped, untyped]

  interface _Function
    def performed?:  -> bool
  end

  class Base
    extend Functions::Callbacks::ClassMethods

    def self.new: -> Functions::Core
    def self.process: (Symbol action_name, ?hash request,  ?Functions::Response response) -> Functions::Response::responseHash
  end
end
