module ActiveFunction
  module Controller
    class Error < StandardError 
    end

    type hash = Hash[untyped, untyped]

    interface _Controller
      def performed?:  -> bool
    end

    class Base
      extend Controller::Callbacks::ClassMethods

      def self.new: -> Controller::Core
      def self.process: (Symbol action_name, ?hash request,  ?Controller::Response response) -> Controller::Response::responseHash
    end
  end 
end
