module ActiveFunction
  class MissingRouteMethod < Error
    MESSAGE_TEMPLATE: String

    attr_reader message: String

    def initialize: (String context) -> void
  end

  class NotRenderedError < Error
    MESSAGE_TEMPLATE: String

    attr_reader message: String

    def initialize: (String context) -> void
  end

  module Functions
    module Core : Base
      include _Function

      @performed: bool
      @action_name: Symbol
      @request: Hash[Symbol, untyped]
      @response: Response
      
      def dispatch: (Symbol action_name, hash request, Response response) -> Response::responseHash

      private

      def process: (Symbol action) -> void
    end
  end
end
