module ActiveFunction
  class MissingRouteMethod < Error
    MESSAGE_TEMPLATE: String

    attr_reader message: String

    def initialize: (String context) -> void
  end

  class NotRenderedError < Error
    MESSAGE_TEMPLATE: String

    attr_reader message: String

    def initialize: (String context) -> void
  end

  module Functions
    module Core : Base
      include _Function

      @performed: bool
      @action_name: Symbol
      @request: Hash[Symbol, untyped]
      @response: Response
      
      def initialize: (Symbol action_name, hash request) -> void
      def process: -> Response::responseHash

      module ClassMethods
        def new: (*untyped) -> Core
        def process: (Symbol action_name, ?request: Hash[Symbol, untyped]) -> Response::responseHash
      end
      
      def self.included: (singleton(Base) base) -> void
    end
  end
end
