module ActiveFunction
  module Functions
    class Response
      type responseHash = {statusCode: Integer, body: String | nil, headers: Hash[String, String]}

      attr_accessor status: Integer
      attr_accessor body: String | nil
      attr_accessor headers: Hash[String, String]

      @committed: bool

      def initialize: (?status: Integer, ?body:  String | nil, ?headers: Hash[String, String]) -> void
      def to_h: -> responseHash
      def commit!: -> void
      def committed?: -> bool
    end
  end 
end
