module ActiveFunction
  class ParameterMissingError < Error
    MESSAGE_TEMPLATE: String

    attr_reader message: String

    def initialize: (untyped param) -> void
  end

  class UnpermittedParameterError < Error
    MESSAGE_TEMPLATE: String

    attr_reader message: String

    def initialize: (untyped param) -> void
  end

  module Functions
    module StrongParameters
      include _Function
      
      @_params: Parameters

      def params: -> Parameters

      class Parameters
        extend Forwardable
        @permitted: bool
        @parameters: hash

        def initialize: (hash parameters, ?permitted: bool) -> void
        def []: (Symbol attribute) -> (Array[Parameters] | Parameters)
        def require: (Symbol attribute) -> (Array[Parameters] | Parameters)
        def permit: (*untyped attributes) -> Parameters
        def to_h: -> hash     

        private

        def nested_attribute: (hash attribute) -> Parameters
          | (Array[hash] attribute) -> Array[Parameters]
          | (untyped attribute) -> untyped

        def process_nested: (untyped attr, Symbol method, ?Array[Symbol] options) -> (Parameters | Array[Parameters] | untyped)

        attr_reader parameters: hash   
      end
    end
  end
end
