module ActiveFunction::Controller
  class DoubleRenderError < Error
    MESSAGE_TEMPLATE: String

    attr_reader message: String

    def initialize: (String context) -> void
  end

  module Rendering : Core
    include _Controller

    DEFAULT_HEADER: Hash[String, String]
    @performed: bool

    def render: (?status: ::Integer, ?json: hash, ?head: hash) -> void
  end
end
