ROUTES: Hash[String, String]

module RBS 
  class Function < ActiveFunction::Base 
    def index: () -> void
    def db_event: () -> void
    
    private 

    def before_action: () -> void
    def after_action: () -> void
    def after_action2: () -> void
    def after_action?: () -> bool
  end 
end 
